### ISSUE TITLE
Unit length for prismatic joints

### ISSUE THREAD

**Issue by harryzhangOG** [warshallrho/VAT-Mart#1]
Hi, thanks for releasing the code. I am curious what the unit length for prismatic joints mentioned in your paper is. I only see the revolute joints' task specification is randomly sampled from 10 to 70 degrees, however, i did not see where the task specification step takes place for prismatic joints. could you point me to it if possible? Thanks.

**Comment by warshallrho** [comment]
Hi @harryzhangOG 
As described in Section 4.1 in the paper, "for the task specification, we randomly sample
within [10, 70] for revolute parts and [0.1, 0.7] for prismatic parts", and thus you can directly set --task_upper to be 0.7 and --task_lower to be 0.1 in args of prismatic joints related experiments.
